trying to fix actions

diff --git a/.github/workflows/bandit.yml b/.github/workflows/bandit.yml
--- a/.github/workflows/bandit.yml
+++ b/.github/workflows/bandit.yml
@@ -1,7 +1,4 @@
-# This workflow will install Python dependencies, run tests and lint with a single version of Python
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
-
-name: Autopep
+name: Bandit Analysis
 
 on:
   push:
@@ -13,7 +10,7 @@ permissions:
   contents: write
 
 jobs:
-  build:
+  bandit:
 
     runs-on: ubuntu-latest
 
@@ -23,15 +20,24 @@ jobs:
       uses: actions/setup-python@v3
       with:
         python-version: "3.12.1"
-    
-     - name: Run Autopep8
+
+    - name: Install Bandit
+      run: pip install bandit
+
+    - name: Run Bandit
       run: |
-        autopep8 --in-place --aggressive --aggressive --recursive . 
+        bandit -r . > logs/bandit/latest_bandit.log
+        if grep -q "No issues identified" logs/bandit/latest_bandit.log; then
+          echo "Bandit Status: success" > badge_status.txt
+        else
+          echo "Bandit Status: failure" > badge_status.txt
+          exit 1
+        fi
 
     - name: Commit Badge Update
       run: |
         git config user.name 'github-actions[bot]'
         git config user.email 'github-actions[bot]@users.noreply.github.com'
         git add badge_status.txt
-        git commit -m "Update Autopep8 badge" || echo "No changes to commit"
+        git commit -m "Update Bandit badge" || echo "No changes to commit"
         git push
